version: '3.3'
services:  
  frontend:
    image: masterhua/234-deploylab-frontend:latest
    ports:
      - "8086:80"
      
  frontend-prod:
    image: masterhua/9999-deploylab-frontend:latest
    ports:
      - "9999:80"